# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1499/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1499/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/popcorn/ims/IMSProject_2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/popcorn/ims/IMSProject_2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1499/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1499/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popcorn/ims/IMSProject_2025/CMakeFiles /home/popcorn/ims/IMSProject_2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popcorn/ims/IMSProject_2025/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popcorn/ims/IMSProject_2025/CMakeFiles /home/popcorn/ims/IMSProject_2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popcorn/ims/IMSProject_2025/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IMS

# Build rule for target.
IMS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMS
.PHONY : IMS

# fast build rule for target.
IMS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/build
.PHONY : IMS/fast

ArgParser/ArgParser.o: ArgParser/ArgParser.cpp.o
.PHONY : ArgParser/ArgParser.o

# target to build an object file
ArgParser/ArgParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/ArgParser/ArgParser.cpp.o
.PHONY : ArgParser/ArgParser.cpp.o

ArgParser/ArgParser.i: ArgParser/ArgParser.cpp.i
.PHONY : ArgParser/ArgParser.i

# target to preprocess a source file
ArgParser/ArgParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/ArgParser/ArgParser.cpp.i
.PHONY : ArgParser/ArgParser.cpp.i

ArgParser/ArgParser.s: ArgParser/ArgParser.cpp.s
.PHONY : ArgParser/ArgParser.s

# target to generate assembly for a file
ArgParser/ArgParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/ArgParser/ArgParser.cpp.s
.PHONY : ArgParser/ArgParser.cpp.s

Cell/Cell.o: Cell/Cell.cpp.o
.PHONY : Cell/Cell.o

# target to build an object file
Cell/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Cell.cpp.o
.PHONY : Cell/Cell.cpp.o

Cell/Cell.i: Cell/Cell.cpp.i
.PHONY : Cell/Cell.i

# target to preprocess a source file
Cell/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Cell.cpp.i
.PHONY : Cell/Cell.cpp.i

Cell/Cell.s: Cell/Cell.cpp.s
.PHONY : Cell/Cell.s

# target to generate assembly for a file
Cell/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Cell.cpp.s
.PHONY : Cell/Cell.cpp.s

Cell/Soil.o: Cell/Soil.cpp.o
.PHONY : Cell/Soil.o

# target to build an object file
Cell/Soil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Soil.cpp.o
.PHONY : Cell/Soil.cpp.o

Cell/Soil.i: Cell/Soil.cpp.i
.PHONY : Cell/Soil.i

# target to preprocess a source file
Cell/Soil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Soil.cpp.i
.PHONY : Cell/Soil.cpp.i

Cell/Soil.s: Cell/Soil.cpp.s
.PHONY : Cell/Soil.s

# target to generate assembly for a file
Cell/Soil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Soil.cpp.s
.PHONY : Cell/Soil.cpp.s

Cell/Terrain.o: Cell/Terrain.cpp.o
.PHONY : Cell/Terrain.o

# target to build an object file
Cell/Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Terrain.cpp.o
.PHONY : Cell/Terrain.cpp.o

Cell/Terrain.i: Cell/Terrain.cpp.i
.PHONY : Cell/Terrain.i

# target to preprocess a source file
Cell/Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Terrain.cpp.i
.PHONY : Cell/Terrain.cpp.i

Cell/Terrain.s: Cell/Terrain.cpp.s
.PHONY : Cell/Terrain.s

# target to generate assembly for a file
Cell/Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Terrain.cpp.s
.PHONY : Cell/Terrain.cpp.s

Cell/Vegetation.o: Cell/Vegetation.cpp.o
.PHONY : Cell/Vegetation.o

# target to build an object file
Cell/Vegetation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Vegetation.cpp.o
.PHONY : Cell/Vegetation.cpp.o

Cell/Vegetation.i: Cell/Vegetation.cpp.i
.PHONY : Cell/Vegetation.i

# target to preprocess a source file
Cell/Vegetation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Vegetation.cpp.i
.PHONY : Cell/Vegetation.cpp.i

Cell/Vegetation.s: Cell/Vegetation.cpp.s
.PHONY : Cell/Vegetation.s

# target to generate assembly for a file
Cell/Vegetation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Cell/Vegetation.cpp.s
.PHONY : Cell/Vegetation.cpp.s

Map/Map.o: Map/Map.cpp.o
.PHONY : Map/Map.o

# target to build an object file
Map/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/Map.cpp.o
.PHONY : Map/Map.cpp.o

Map/Map.i: Map/Map.cpp.i
.PHONY : Map/Map.i

# target to preprocess a source file
Map/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/Map.cpp.i
.PHONY : Map/Map.cpp.i

Map/Map.s: Map/Map.cpp.s
.PHONY : Map/Map.s

# target to generate assembly for a file
Map/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/Map.cpp.s
.PHONY : Map/Map.cpp.s

Map/MapParser.o: Map/MapParser.cpp.o
.PHONY : Map/MapParser.o

# target to build an object file
Map/MapParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/MapParser.cpp.o
.PHONY : Map/MapParser.cpp.o

Map/MapParser.i: Map/MapParser.cpp.i
.PHONY : Map/MapParser.i

# target to preprocess a source file
Map/MapParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/MapParser.cpp.i
.PHONY : Map/MapParser.cpp.i

Map/MapParser.s: Map/MapParser.cpp.s
.PHONY : Map/MapParser.s

# target to generate assembly for a file
Map/MapParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Map/MapParser.cpp.s
.PHONY : Map/MapParser.cpp.s

Simulator/OutputWindow.o: Simulator/OutputWindow.cpp.o
.PHONY : Simulator/OutputWindow.o

# target to build an object file
Simulator/OutputWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/OutputWindow.cpp.o
.PHONY : Simulator/OutputWindow.cpp.o

Simulator/OutputWindow.i: Simulator/OutputWindow.cpp.i
.PHONY : Simulator/OutputWindow.i

# target to preprocess a source file
Simulator/OutputWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/OutputWindow.cpp.i
.PHONY : Simulator/OutputWindow.cpp.i

Simulator/OutputWindow.s: Simulator/OutputWindow.cpp.s
.PHONY : Simulator/OutputWindow.s

# target to generate assembly for a file
Simulator/OutputWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/OutputWindow.cpp.s
.PHONY : Simulator/OutputWindow.cpp.s

Simulator/Simulator.o: Simulator/Simulator.cpp.o
.PHONY : Simulator/Simulator.o

# target to build an object file
Simulator/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/Simulator.cpp.o
.PHONY : Simulator/Simulator.cpp.o

Simulator/Simulator.i: Simulator/Simulator.cpp.i
.PHONY : Simulator/Simulator.i

# target to preprocess a source file
Simulator/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/Simulator.cpp.i
.PHONY : Simulator/Simulator.cpp.i

Simulator/Simulator.s: Simulator/Simulator.cpp.s
.PHONY : Simulator/Simulator.s

# target to generate assembly for a file
Simulator/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Simulator/Simulator.cpp.s
.PHONY : Simulator/Simulator.cpp.s

Species/SpeciesInfo.o: Species/SpeciesInfo.cpp.o
.PHONY : Species/SpeciesInfo.o

# target to build an object file
Species/SpeciesInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesInfo.cpp.o
.PHONY : Species/SpeciesInfo.cpp.o

Species/SpeciesInfo.i: Species/SpeciesInfo.cpp.i
.PHONY : Species/SpeciesInfo.i

# target to preprocess a source file
Species/SpeciesInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesInfo.cpp.i
.PHONY : Species/SpeciesInfo.cpp.i

Species/SpeciesInfo.s: Species/SpeciesInfo.cpp.s
.PHONY : Species/SpeciesInfo.s

# target to generate assembly for a file
Species/SpeciesInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesInfo.cpp.s
.PHONY : Species/SpeciesInfo.cpp.s

Species/SpeciesRegistry.o: Species/SpeciesRegistry.cpp.o
.PHONY : Species/SpeciesRegistry.o

# target to build an object file
Species/SpeciesRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesRegistry.cpp.o
.PHONY : Species/SpeciesRegistry.cpp.o

Species/SpeciesRegistry.i: Species/SpeciesRegistry.cpp.i
.PHONY : Species/SpeciesRegistry.i

# target to preprocess a source file
Species/SpeciesRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesRegistry.cpp.i
.PHONY : Species/SpeciesRegistry.cpp.i

Species/SpeciesRegistry.s: Species/SpeciesRegistry.cpp.s
.PHONY : Species/SpeciesRegistry.s

# target to generate assembly for a file
Species/SpeciesRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/Species/SpeciesRegistry.cpp.s
.PHONY : Species/SpeciesRegistry.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMS.dir/build.make CMakeFiles/IMS.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IMS"
	@echo "... ArgParser/ArgParser.o"
	@echo "... ArgParser/ArgParser.i"
	@echo "... ArgParser/ArgParser.s"
	@echo "... Cell/Cell.o"
	@echo "... Cell/Cell.i"
	@echo "... Cell/Cell.s"
	@echo "... Cell/Soil.o"
	@echo "... Cell/Soil.i"
	@echo "... Cell/Soil.s"
	@echo "... Cell/Terrain.o"
	@echo "... Cell/Terrain.i"
	@echo "... Cell/Terrain.s"
	@echo "... Cell/Vegetation.o"
	@echo "... Cell/Vegetation.i"
	@echo "... Cell/Vegetation.s"
	@echo "... Map/Map.o"
	@echo "... Map/Map.i"
	@echo "... Map/Map.s"
	@echo "... Map/MapParser.o"
	@echo "... Map/MapParser.i"
	@echo "... Map/MapParser.s"
	@echo "... Simulator/OutputWindow.o"
	@echo "... Simulator/OutputWindow.i"
	@echo "... Simulator/OutputWindow.s"
	@echo "... Simulator/Simulator.o"
	@echo "... Simulator/Simulator.i"
	@echo "... Simulator/Simulator.s"
	@echo "... Species/SpeciesInfo.o"
	@echo "... Species/SpeciesInfo.i"
	@echo "... Species/SpeciesInfo.s"
	@echo "... Species/SpeciesRegistry.o"
	@echo "... Species/SpeciesRegistry.i"
	@echo "... Species/SpeciesRegistry.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

